# sparsegrad tutorial

In [1]:
import sparsegrad

## Testing installation

In [2]:
sparsegrad.test()

Running unit tests for sparsegrad
NumPy version 1.13.3
NumPy relaxed strides checking option: True
NumPy is installed in /usr/lib/python3.6/site-packages/numpy
Python version 3.6.4 (default, Dec 23 2017, 19:07:07) [GCC 7.2.1 20171128]
nose version 1.3.7


....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
----------------------------------------------------------------------
Ran 676 tests in 1.340s

OK


<nose.result.TextTestResult run=676 errors=0 failures=0>

## Calculation of Jacobian

In [3]:
import numpy as np
import sparsegrad as ad

In [4]:
def function(x):
    return np.exp(-x**2)

In [5]:
x0=np.linspace(-1,1,5)

Calculate value and function gradient by forward mode automatic differentiation:

In [6]:
y=function(ad.forward.seed_sparse_gradient(x0))

Access function value:

In [7]:
y.value

array([ 0.36787944,  0.77880078,  1.        ,  0.77880078,  0.36787944])

Access gradient as sparse matrix:

In [8]:
y.dvalue.tocsr()

<5x5 sparse matrix of type '<class 'numpy.float64'>'
	with 5 stored elements in Compressed Sparse Row format>

In [9]:
print(y.dvalue.toarray())

[[ 0.73575888  0.          0.          0.          0.        ]
 [ 0.          0.77880078  0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.         -0.77880078  0.        ]
 [ 0.          0.          0.          0.         -0.73575888]]


## Calculation of sparsity pattern

In [10]:
y=function(ad.forward.seed_sparsity(np.zeros_like(x0)))

Access positions of possible nonzeros in AIJ format:

In [11]:
y.sparsity.indices

array([0, 1, 2, 3, 4], dtype=int32)

In [12]:
y.sparsity.indptr

array([0, 1, 2, 3, 4, 5], dtype=int32)

Access positions of possible nonzeros as scipy CSR matrix:

In [13]:
y.sparsity.tocsr()

<5x5 sparse matrix of type '<class 'numpy.int64'>'
	with 5 stored elements in Compressed Sparse Row format>

In [14]:
print(y.sparsity.tocsr().toarray())

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
